<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="stjpb">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forljy" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="utghy" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pllxiqcli" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kvqqidp" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qefvzdmafu" eType="#//hlwyfrebfq"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="psennz" eType="#//zbacnboy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jqbxym" eType="#//johvrje"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iryofgs" eType="#//csbnikwxe"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="erywy" eType="#//wrffpvlsn"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="buqivcuz">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zxlftsix" eType="#//dataTypes/gogmrz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="prhdqga">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="4"/>
      <details key="polygon.x" value="16"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gpuywg" eType="#//dataTypes/fzuel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="tzpvzsdqew">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etvcqxe" eType="#//dataTypes/gogmrz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="xhsdsq">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mdxfm">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="19"/>
      <details key="polygon.x" value="9"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eihetrb" eType="#//dataTypes/zvovur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="cfokr">
    <eAnnotations source="gmf.node">
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="cdnmclkp"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="cxrrudpyu">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="szswbl" eType="#//dataTypes/gogmrz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="hlwyfrebfq">
    <eAnnotations source="gmf.link">
      <details key="source" value="hamqvcjtql"/>
      <details key="target" value="vjgxsfdl"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//zbacnboy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//johvrje"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//csbnikwxe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hamqvcjtql" eType="#//wrffpvlsn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//zbacnboy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//johvrje"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//csbnikwxe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjgxsfdl" eType="#//wrffpvlsn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="zbacnboy">
    <eAnnotations source="gmf.link">
      <details key="source" value="rgpbtz"/>
      <details key="target" value="igptht"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//hlwyfrebfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//johvrje"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//csbnikwxe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rgpbtz" eType="#//wrffpvlsn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//hlwyfrebfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//johvrje"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//csbnikwxe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="igptht" eType="#//wrffpvlsn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="johvrje">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="closedarrow"/>
      <details key="target.decoration" value="filledclosedarrow"/>
      <details key="source" value="gtanxvyxbz"/>
      <details key="target" value="yfhulap"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qtnjbbx" eType="#//dataTypes/tzzqbjd"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kgugxes" eType="#//dataTypes/fzuel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="betfn" eType="#//dataTypes/gogmrz"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fbyubrp" eType="#//dataTypes/gogmrz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//hlwyfrebfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//zbacnboy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//csbnikwxe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gtanxvyxbz" eType="#//wrffpvlsn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//hlwyfrebfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//zbacnboy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//csbnikwxe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yfhulap" eType="#//wrffpvlsn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="csbnikwxe">
    <eAnnotations source="gmf.link">
      <details key="source" value="ucmyhd"/>
      <details key="target" value="hzwcqseehk"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//hlwyfrebfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//zbacnboy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//johvrje"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ucmyhd" eType="#//wrffpvlsn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//hlwyfrebfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//zbacnboy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//johvrje"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hzwcqseehk" eType="#//wrffpvlsn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="wrffpvlsn">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="closedarrow"/>
      <details key="target.decoration" value="filledsquare"/>
      <details key="source" value="hbrmcahhpg"/>
      <details key="target" value="sotwc"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zkszg" eType="#//dataTypes/vuwegsmulh"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//hlwyfrebfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//zbacnboy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//johvrje"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hbrmcahhpg" eType="#//csbnikwxe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//stjpb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//buqivcuz"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//prhdqga"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//tzpvzsdqew"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//xhsdsq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//mdxfm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//cfokr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//cxrrudpyu"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//hlwyfrebfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//zbacnboy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//johvrje"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sotwc" eType="#//csbnikwxe"/>
  </eClassifiers>
  <eSubpackages name="dataTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="tzzqbjd"/>
    <eClassifiers xsi:type="ecore:EDataType" name="gogmrz"/>
    <eClassifiers xsi:type="ecore:EDataType" name="zvovur"/>
    <eClassifiers xsi:type="ecore:EDataType" name="vuwegsmulh"/>
    <eClassifiers xsi:type="ecore:EDataType" name="fzuel"/>
  </eSubpackages>
</ecore:EPackage>
