<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MyEcore">
  <eClassifiers xsi:type="ecore:EClass" name="3B1OUOCQ">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcbpkul" eType="#//Dodrio_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rcvcsif" eType="#//Farfetch%27d_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zrgwsmd" eType="#//Porygon_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zfwyghr" eType="#//Eevee_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usvpyle" eType="#//Golbat_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fboajen" eType="#//Rhyhorn_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hnluetr" eType="#//Pinsir_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jwymswr" eType="#//Wartortle_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vekdhpp" eType="#//Rhydon_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gnugvil" eType="#//Omanyte_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wdtqfwl" eType="#//Dodrio_N.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ijzivag" eType="#//Farfetch%27d_N.1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwcderx" eType="#//Slowpoke_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rvjzpnz" eType="#//Drowzee_L"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jffulzf" eType="#//Squirtle_L"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobmqjb" eType="#//Machop_L"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ldultmz" eType="#//Machoke_L"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fdhmafw" eType="#//Omanyte_L"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="zUStF98"/>
  <eClassifiers xsi:type="ecore:EDataType" name="doxdnfC"/>
  <eClassifiers xsi:type="ecore:EDataType" name="j6UkIsw"/>
  <eClassifiers xsi:type="ecore:EDataType" name="hXaUXzZ"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Ii9axxS"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dodrio_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="3"/>
      <details key="polygon.x" value="8"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Farfetch'd_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="20"/>
      <details key="polygon.x" value="6"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Porygon_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="10"/>
      <details key="polygon.x" value="13"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eevee_N">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cesky Terrier" eType="#//j6UkIsw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Golbat_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rhyhorn_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="0"/>
      <details key="polygon.x" value="15"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pinsir_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wartortle_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rhydon_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="ftp://www.JsHmqMRDr.net:3877/iylgg/vyiiw/#%[=bOF8"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Omanyte_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="19"/>
      <details key="polygon.x" value="13"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dodrio_N">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Great Pyrenees" eType="#//j6UkIsw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Irish Setter" eType="#//hXaUXzZ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Farfetch'd_N">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Puli" eType="#//j6UkIsw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardigan Welsh Corgi" eType="#//hXaUXzZ"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Whippet" eType="#//zUStF98"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slowpoke_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="15"/>
      <details key="polygon.x" value="2"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lickitung_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ditto_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lickitung_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Weepinbell_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="20"/>
      <details key="polygon.x" value="10"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Affenpinscher" eType="#//j6UkIsw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Briard" eType="#//j6UkIsw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Shiba Inu" eType="#//zUStF98"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Haunter_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="ssh://www.PlYiSaM.net/xpkp/cdngae/bbriml/fecgxt/#IBl@kwu?G"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Black and Tan Coonhound"
        eType="#//hXaUXzZ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Poliwag_N">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Great Pyrenees" eType="#//Ii9axxS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Golduck_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="15"/>
      <details key="polygon.x" value="18"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Greyhound" eType="#//zUStF98"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Spearow_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metapod_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Horsea_N">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Harrier" eType="#//hXaUXzZ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ninetales_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dragonite_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="10"/>
      <details key="polygon.x" value="10"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hitmonlee_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="0"/>
      <details key="polygon.x" value="10"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ditto_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Jolteon_N">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Articuno_N">
    <eAnnotations source="gmf.node">
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="ssh://www.iwWkFsz.edu/#*woehhgu.)_"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nidorino_N">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="English Foxhound" eType="#//j6UkIsw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="English Cocker Spaniel"
        eType="#//j6UkIsw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pointer" eType="#//Ii9axxS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Chinook" eType="#//j6UkIsw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drowzee_L">
    <eAnnotations source="gmf.link">
      <details key="source" value="eQXWYdb"/>
      <details key="target" value="r1FzEWq"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eQXWYdb" eType="#//3B1OUOCQ"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="r1FzEWq" eType="#//3B1OUOCQ"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Squirtle_L">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="closedarrow"/>
      <details key="target.decoration" value="closedarrow"/>
      <details key="source" value="6MHm83A"/>
      <details key="target" value="flrzx31"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="6MHm83A" eType="#//Dodrio_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flrzx31" eType="#//Dodrio_N"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machop_L">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="filledclosedarrow"/>
      <details key="target.decoration" value="closedarrow"/>
      <details key="source" value="oALdOH5"/>
      <details key="target" value="L3QCddr"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Doberman Pinscher" eType="#//doxdnfC"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Irish Red and White Setter"
        eType="#//hXaUXzZ"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Airedale Terrier" eType="#//j6UkIsw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oALdOH5" eType="#//Farfetch%27d_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="L3QCddr" eType="#//Farfetch%27d_N"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machoke_L">
    <eAnnotations source="gmf.link">
      <details key="source" value="1Y7Kf88"/>
      <details key="target" value="KT9kFQ9"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="1Y7Kf88" eType="#//Porygon_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="KT9kFQ9" eType="#//Porygon_N"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Omanyte_L">
    <eAnnotations source="gmf.link">
      <details key="source" value="5u3KvNE"/>
      <details key="target" value="YDLm57N"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Collie" eType="#//j6UkIsw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Afghan Hound" eType="#//doxdnfC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="5u3KvNE" eType="#//Eevee_N"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="YDLm57N" eType="#//Eevee_N"/>
  </eClassifiers>
</ecore:EPackage>
