<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="ecore">
    <eClassifiers xsi:type="ecore:EClass" name="oghfpwlvl">
      <eAnnotations source="gmf.diagram">
        <details key="svg.uri" value="xykpu"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="yyzmdj" eType="/0/psbqgtj"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qubvbwejb" eType="/0/lkfngvyaqt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dhzcjtmdag" eType="/0/aolswgbee"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dsvzfsdgv" eType="/0/jpzhvmd"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sscevim" eType="/0/saqhl">
        <eAnnotations source="gmf.link">
          <details key="source.decoration" value="square"/>
          <details key="target.decoration" value="arrow"/>
          <details key="source" value="orrxjfn"/>
          <details key="target" value="wuuevrcc"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xxvwnc" eType="/0/dsypypx"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="yzenys" eType="/0/yhasokfry" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iqyqo" eType="/0/ttlusrc" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="czifmtjnmf" eType="/0/uwtim" containment="true">
        <eAnnotations source="gmf.link">
          <details key="source" value="fqdyddvl"/>
          <details key="target" value="hrvvaut"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="vurft" eType="/0/fwnnpywa" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xuihbrhceo" eType="/0/vhylzimx" containment="true">
        <eAnnotations source="gmf.compartment"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="psbqgtj">
      <eAnnotations source="gmf.node">
        <details key="figure" value="polygon"/>
        <details key="polygon.y" value="15"/>
        <details key="polygon.x" value="18"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="lkfngvyaqt">
      <eAnnotations source="gmf.node"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="aolswgbee">
      <eAnnotations source="gmf.node">
        <details key="figure" value="svg"/>
        <details key="svg.uri" value="ccpbwdve"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="njsqq" eType="/21"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tmgcntjjaq" eType="/22"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bzbxotdznf" eType="/22"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="jpzhvmd">
      <eAnnotations source="gmf.node"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="saqhl">
      <eAnnotations source="gmf.node"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="dsypypx">
      <eAnnotations source="gmf.node">
        <details key="figure" value="polygon"/>
        <details key="polygon.y" value="14"/>
        <details key="polygon.x" value="14"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ryqbsri">
      <eAnnotations source="gmf.node"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="yhasokfry">
      <eAnnotations source="gmf.link">
        <details key="source" value="wdysyn"/>
        <details key="target" value="jzovur"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="wdysyn" eType="/0/saqhl"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jzovur" eType="/0/dsypypx"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ttlusrc">
      <eAnnotations source="gmf.link">
        <details key="source.decoration" value="arrow"/>
        <details key="target.decoration" value="arrow"/>
        <details key="source" value="gsqex"/>
        <details key="target" value="iwupx"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="gsqex" eType="/0/ttlusrc"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iwupx" eType="/0/aolswgbee"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="uwtim">
      <eAnnotations source="gmf.link">
        <details key="source.decoration" value="closedarrow"/>
        <details key="target.decoration" value="rhomb"/>
        <details key="source" value="bmrxztb"/>
        <details key="target" value="qpangbqh"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="slnhds" eType="/21"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fnisdpemc" eType="/23"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="eiowmcstm" eType="/24"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="okvgwlxy" eType="/22"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bmrxztb" eType="/0/uwtim"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qpangbqh" eType="/0/aolswgbee"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="fwnnpywa">
      <eAnnotations source="gmf.link">
        <details key="source.decoration" value="closedarrow"/>
        <details key="target.decoration" value="rhomb"/>
        <details key="source" value="pmveykg"/>
        <details key="target" value="zgodomyk"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pmveykg" eType="/0/dsypypx"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="zgodomyk" eType="/0/vhylzimx"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="vhylzimx">
      <eAnnotations source="gmf.link">
        <details key="source" value="cemdhiqrt"/>
        <details key="target" value="kmpvmwf"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ljodoi" eType="/21"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ykfygmszuv" eType="/22"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="txxgejpjdq" eType="/24"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cemdhiqrt" eType="/0/ttlusrc"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="kmpvmwf" eType="/0/aolswgbee"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EAttribute name="cotcksdry" eType="/22"/>
  <ecore:EAttribute name="nlravfq" eType="/24"/>
  <ecore:EAttribute name="yzkbgnval" eType="/21"/>
  <ecore:EAttribute name="hwuzbcb" eType="/23"/>
  <ecore:EAttribute name="xkvczpvzqx" eType="/24"/>
  <ecore:EAttribute name="zbbyk" eType="/21"/>
  <ecore:EAttribute name="xskioclgb" eType="/23"/>
  <ecore:EAttribute name="escknepw" eType="/21"/>
  <ecore:EAttribute name="njhippeaot" eType="/21"/>
  <ecore:EAttribute name="xctry" eType="/25"/>
  <ecore:EStringToStringMapEntry key="ruobeyh" value="mbrjxttw"/>
  <ecore:EStringToStringMapEntry key="tscgo" value="uxfdzam"/>
  <ecore:EStringToStringMapEntry key="vehuroe" value="thqamll"/>
  <ecore:EStringToStringMapEntry key="khxarc" value="rxozo"/>
  <ecore:EStringToStringMapEntry key="kydzmx" value="rxcxnay"/>
  <ecore:EStringToStringMapEntry key="hpaskln" value="sznaqr"/>
  <ecore:EStringToStringMapEntry key="wsaru" value="emnrrjhgg"/>
  <ecore:EStringToStringMapEntry key="wdpflc" value="xjwbgiuiys"/>
  <ecore:EStringToStringMapEntry key="nglfdog" value="uvpktd"/>
  <ecore:EStringToStringMapEntry key="vxvwmhx" value="mucybmvqv"/>
  <ecore:EDataType name="ayektgbe"/>
  <ecore:EDataType name="yrrbqtvi"/>
  <ecore:EDataType name="jpupb"/>
  <ecore:EDataType name="csyvbco"/>
  <ecore:EDataType name="uwzkoxvlk"/>
</xmi:XMI>
