<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EClass name="oghfpw">
    <eAnnotations source="gmf.diagram">
      <details key="source" value="key"/>
      <details key="target" value="svg.uri"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="swgbeehw" eType="/2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ccpbwd" eType="/4"/>
  </ecore:EClass>
  <ecore:EClass name="vlumau">
    <eAnnotations source="gmf.node"/>
  </ecore:EClass>
  <ecore:EClass name="kagpsbqgt">
    <eAnnotations source="gmf.node"/>
  </ecore:EClass>
  <ecore:EClass name="warzw">
    <eAnnotations source="gmf.node"/>
  </ecore:EClass>
  <ecore:EClass name="lkfngvya">
    <eAnnotations source="gmf.node"/>
  </ecore:EClass>
  <ecore:EClass name="tcwiao">
    <eAnnotations source="gmf.node"/>
  </ecore:EClass>
</xmi:XMI>
