<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="oghfpwlvl">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="saqhl" eType="//jpzhvmd" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mdsypy" eType="//xotdzn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pxmbdary" eType="//wgbee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bsrilaayh" eType="//cntjjaqjb" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mauak">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="psbqgtj">
    <eAnnotations source="gmf.node">
      <details key="label.placement" value="none"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="wgbee">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="closedarrow"/>
      <details key="target.decoration" value="filledrhomb"/>
      <details key="source" value="arzwblk"/>
      <details key="target" value="ngvyaqtcwi"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arzwblk" eType="//psbqgtj" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ngvyaqtcwi" eType="//wgbee" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="cntjjaqjb">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="filledrhomb"/>
      <details key="target.decoration" value="arrow"/>
      <details key="source" value="wbccpbwd"/>
      <details key="target" value="eukoknjsqq"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wbccpbwd" eType="//mauak" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eukoknjsqq" eType="//xotdzn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="xotdzn">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="jpzhvmd">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
