<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore" nsURI="http://www.eclipse.org/emf/2002/Ecore" nsPrefix="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="Student">
    <eAnnotations source="gmf.diagram">
      <details key="source" value="go"/>
      <details key="target" value="me"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="vlumau">
    <eAnnotations source="gmf.node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" eType="//Student" containment="true">
      <eAnnotations source="source"/>
      <eAnnotations source="gmf.compartment">
        <details key="source" value="name"/>
        <details key="target" value="svg.uri"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
