<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="schoolRoom">
  <School name="oghfpw"/>
  <SchoolRoom name="vlumau"/>
  <SchoolRoom name="kagpsbqgt"/>
  <SchoolRoom name="warzw"/>
  <SchoolRoom name="lkfngvya"/>
  <SchoolRoom name="tcwiao"/>
  <Clock name="swgbeehw"/>
  <Buzzer name="ccpbwd"/>
</xmi:XMI>
