<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="student">
  <Student name="Student oghfpw" award="/5 /6 /8"/>
  <Student name="Student vlumau" award="/7"/>
  <Student name="Student kagpsbqgt"/>
  <Student name="Student warzw" award="/9"/>
  <Student name="Student lkfngvya" award="/10"/>
  <Prize name="Prize tcwiao" sponsor="/13 /11" student="/0"/>
  <Prize name="Prize swgbeehw" sponsor="/12 /11" student="/0"/>
  <Prize name="Prize ccpbwd" sponsor="/11 /12" student="/1"/>
  <Prize name="Prize eukoknjsq" sponsor="/13" student="/0"/>
  <Prize name="Prize ntmgcn" sponsor="/11" student="/3"/>
  <Prize name="Prize jjaqjbz" sponsor="/12" student="/4"/>
  <Sponsor name="Sponsor xotdznfs" prize="/5 /6 /7 /9"/>
  <Sponsor name="Sponsor pzhvm" prize="/6 /7 /10"/>
  <Sponsor name="Sponsor dzusa" prize="/5 /8"/>
  <Sponsor name="Sponsor hlpbmdsy"/>
</xmi:XMI>
