<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="kgrxppk">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zsxsj" eType="//elbvhg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ueeugm" eType="//jcrshng"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wrofzk" eType="//rihpilo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scfdeuo" eType="//abiinqde"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="egpwmwh" eType="//ydsesv" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ogfvaxucuo" eType="//hjisn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tmiokzefq" eType="//jvqvp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gfplns" eType="//rqhhcssuym" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dvsxckq" eType="//lucvrlv" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="elbvhg">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="6"/>
      <details key="polygon.x" value="10"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="erlwwwoa" eType="//dataTypes/modbrboic"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wykkvumzzj" eType="//dataTypes/ilvlvlyl"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jmfct" eType="//dataTypes/wkbqifizds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="jcrshng">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="rihpilo">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="8"/>
      <details key="polygon.x" value="4"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zejgdzkwpk" eType="//dataTypes/ilvlvlyl"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bvvwu" eType="//dataTypes/wkbqifizds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="abiinqde">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="pwoppsckdc">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="11"/>
      <details key="polygon.x" value="0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="vydhth">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="gfwsetkm">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="0"/>
      <details key="polygon.x" value="2"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="dgjejce">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="rwuwwvnd">
    <eAnnotations source="gmf.node">
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="lijglm"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ydsesv">
    <eAnnotations source="gmf.link">
      <details key="source" value="vblqonlgur"/>
      <details key="target" value="nyknvsif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vblqonlgur" eType="//kgrxppk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nyknvsif" eType="//kgrxppk"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="hjisn">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="filledrhomb"/>
      <details key="target.decoration" value="arrow"/>
      <details key="source" value="vjxqhryz"/>
      <details key="target" value="bnhlbae"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vjxqhryz" eType="//elbvhg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bnhlbae" eType="//elbvhg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="jvqvp">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="closedarrow"/>
      <details key="target.decoration" value="arrow"/>
      <details key="source" value="jmvanux"/>
      <details key="target" value="mdvwmjyhq"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="glltaxwbz" eType="//dataTypes/xjjqkaywmw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jmvanux" eType="//jcrshng"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mdvwmjyhq" eType="//jcrshng"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="rqhhcssuym">
    <eAnnotations source="gmf.link">
      <details key="source" value="guawoijjz"/>
      <details key="target" value="eefhqc"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vswlsfwck" eType="//dataTypes/wgfdtnhq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guawoijjz" eType="//rihpilo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eefhqc" eType="//rihpilo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lucvrlv">
    <eAnnotations source="gmf.link">
      <details key="source" value="khpivvwup"/>
      <details key="target" value="mfsiouzh"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="igkmhlwish" eType="//dataTypes/xjjqkaywmw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="khpivvwup" eType="//abiinqde"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mfsiouzh" eType="//abiinqde"/>
  </eClassifiers>
  <eSubpackages name="dataTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="wgfdtnhq"/>
    <eClassifiers xsi:type="ecore:EDataType" name="wkbqifizds"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ilvlvlyl"/>
    <eClassifiers xsi:type="ecore:EDataType" name="xjjqkaywmw"/>
    <eClassifiers xsi:type="ecore:EDataType" name="modbrboic"/>
  </eSubpackages>
</ecore:EPackage>
