<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="rgxgvmtwof">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prjkrvcf" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mysubgwh" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foanukaaif" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asfrzle" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uhjmjhx" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vwdqdqwwl" eType="#//olwlijmuek"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="agsbnqod" eType="#//yejzgrca"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="peqeb" eType="#//pzomq"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ybqjiarv" eType="#//pvqitipe"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jrjiq" eType="#//gcfptg"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="blkquvk">
    <eAnnotations source="gmf.node">
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="hhbspziu"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yhdwifrd" eType="#//dataTypes/kibys"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="weimirt">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="0"/>
      <details key="polygon.x" value="19"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="jgbbptyx">
    <eAnnotations source="gmf.node">
      <details key="figure" value="polygon"/>
      <details key="polygon.y" value="13"/>
      <details key="polygon.x" value="0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gguehr" eType="#//dataTypes/ruaymmybrh"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ythhddkl" eType="#//dataTypes/ruaymmybrh"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kzeqdpgvfb" eType="#//dataTypes/kibys"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ylwktrpqax" eType="#//dataTypes/wrsthw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ebfwuqcob">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="xgstynrk">
    <eAnnotations source="gmf.node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lpqeoezkfq">
    <eAnnotations source="gmf.node">
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="lmphzj"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="lqmlnfkmru">
    <eAnnotations source="gmf.node">
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="droiact"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qqzfdhfb" eType="#//dataTypes/kibys"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="olwlijmuek">
    <eAnnotations source="gmf.link">
      <details key="source" value="qvmasmhtl"/>
      <details key="target" value="hfpvrve"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//yejzgrca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//pzomq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//pvqitipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qvmasmhtl" eType="#//gcfptg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//yejzgrca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//pzomq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//pvqitipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hfpvrve" eType="#//gcfptg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="yejzgrca">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="filledsquare"/>
      <details key="target.decoration" value="filledclosedarrow"/>
      <details key="source" value="pdtrl"/>
      <details key="target" value="bckcasi"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//olwlijmuek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//pzomq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//pvqitipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pdtrl" eType="#//gcfptg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//olwlijmuek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//pzomq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//pvqitipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bckcasi" eType="#//gcfptg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="pzomq">
    <eAnnotations source="gmf.link">
      <details key="source.decoration" value="square"/>
      <details key="target.decoration" value="filledclosedarrow"/>
      <details key="source" value="krafvw"/>
      <details key="target" value="fwhfe"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hmyra" eType="#//dataTypes/yksygs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icculepg" eType="#//dataTypes/yksygs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//olwlijmuek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//yejzgrca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//pvqitipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="krafvw" eType="#//gcfptg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//olwlijmuek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//yejzgrca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//pvqitipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fwhfe" eType="#//gcfptg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="pvqitipe">
    <eAnnotations source="gmf.link">
      <details key="source" value="mehkmradx"/>
      <details key="target" value="netkazemv"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="klglcpmnzg" eType="#//dataTypes/ruaymmybrh"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="egnewa" eType="#//dataTypes/wrsthw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//olwlijmuek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//yejzgrca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//pzomq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mehkmradx" eType="#//gcfptg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//olwlijmuek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//yejzgrca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//pzomq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="netkazemv" eType="#//gcfptg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="gcfptg">
    <eAnnotations source="gmf.link">
      <details key="source" value="soclsnotf"/>
      <details key="target" value="fugeqgh"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fogovj" eType="#//dataTypes/wrsthw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vaozfcbgn" eType="#//dataTypes/tunjpeva"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//olwlijmuek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//yejzgrca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//pzomq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soclsnotf" eType="#//pvqitipe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//rgxgvmtwof"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//blkquvk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//weimirt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//jgbbptyx"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//ebfwuqcob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//xgstynrk"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//lpqeoezkfq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//lqmlnfkmru"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//olwlijmuek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//yejzgrca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//pzomq"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fugeqgh" eType="#//pvqitipe"/>
  </eClassifiers>
  <eSubpackages name="dataTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="ruaymmybrh"/>
    <eClassifiers xsi:type="ecore:EDataType" name="tunjpeva"/>
    <eClassifiers xsi:type="ecore:EDataType" name="kibys"/>
    <eClassifiers xsi:type="ecore:EDataType" name="yksygs"/>
    <eClassifiers xsi:type="ecore:EDataType" name="wrsthw"/>
  </eSubpackages>
</ecore:EPackage>
